/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AccountStatus = "active" | "checkpoint" | "connecting" | "disconnected" | "paused" | "warming_up";

export type ActionType = "add_tag" | "connect_request" | "endorse_skill" | "enrich" | "fire_webhook" | "follow" | "inmail" | "like_post" | "linkedin_message" | "move_to_campaign" | "send_email" | "visit_profile" | "wait";

export type CampaignStatus = "active" | "archived" | "draft" | "paused";

export type Channel = "email" | "linkedin";

export type ConditionType = "if_connected" | "if_email_clicked" | "if_email_opened" | "if_followed_by_you" | "if_has_email" | "if_inmail_opened" | "if_post_liked" | "if_profile_visited" | "if_replied";

export type DeliveryStatus = "dead" | "delivered" | "failed" | "pending";

export type DnsCheck = "fail" | "not_set" | "pass";

export type EnrollmentStatus = "active" | "failed" | "finished" | "paused" | "replied" | "stopped" | "waiting";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string>;

export type JobStatus = "canceled" | "failed" | "queued" | "running" | "scheduled" | "sent";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LeadStatus = "accepted" | "blacklisted" | "invited" | "new" | "replied" | "unqualified";

export type MembershipRole = "admin" | "member" | "owner";

export type MessageDirection = "me" | "them";

export type Numeric = ColumnType<string, number | string>;

export type SecretKind = "email_oauth" | "email_smtp" | "integration_credentials" | "linkedin_password" | "linkedin_session" | "linkedin_totp" | "user_totp";

export type StepKind = "action" | "condition";

export type SubscriptionStatus = "active" | "canceled" | "past_due" | "trialing";

export type Timestamp = ColumnType<Date, Date | string>;

export type TwofaStatus = "not_set" | "skipped" | "verified";

export interface AbTests {
  campaign_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  metric: Generated<string>;
  min_sends: Generated<number>;
  name: string;
  status: Generated<string>;
  step_id: string | null;
  workspace_id: string;
}

export interface AbVariants {
  id: Generated<string>;
  label: string;
  template_id: string;
  test_id: string;
}

export interface Activity {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  refs: Generated<Json>;
  text: string;
  tone: Generated<string>;
  workspace_id: string;
}

export interface ApiKeys {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  key_hash: string;
  key_prefix: string;
  last_used_at: Timestamp | null;
  name: string;
  revoked_at: Timestamp | null;
  scopes: Generated<string[]>;
  workspace_id: string;
}

export interface AuditLog {
  action: string;
  created_at: Generated<Timestamp>;
  entity: string | null;
  entity_id: string | null;
  id: Generated<string>;
  ip: string | null;
  meta: Generated<Json>;
  user_id: string | null;
  workspace_id: string | null;
}

export interface Blacklist {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  value: string;
  workspace_id: string;
}

export interface Campaigns {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  daily_cap: Generated<number>;
  email_account_id: string | null;
  entry_step_id: string | null;
  id: Generated<string>;
  linkedin_account_id: string | null;
  name: string;
  status: Generated<CampaignStatus>;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface CampaignStats {
  accepted_pct: Numeric | null;
  campaign_id: string | null;
  leads: Int8 | null;
  replied_pct: Numeric | null;
  sent: Int8 | null;
  workspace_id: string | null;
}

export interface CampaignSteps {
  action: ActionType | null;
  campaign_id: string;
  condition: ConditionType | null;
  delay_hours: Generated<number>;
  id: Generated<string>;
  kind: StepKind;
  next_step_id: string | null;
  on_false_step_id: string | null;
  on_true_step_id: string | null;
  params: Generated<Json>;
  position: Generated<Json>;
  template_id: string | null;
}

export interface DailyStats {
  accepted: Generated<number>;
  day: Timestamp;
  emails_sent: Generated<number>;
  invites_sent: Generated<number>;
  linkedin_account_id: string;
  replies: Generated<number>;
  workspace_id: string;
}

export interface EmailAccounts {
  connected_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  credentials_secret_id: string | null;
  daily_limit: Generated<number>;
  dkim_status: Generated<DnsCheck>;
  dmarc_status: Generated<DnsCheck>;
  dns_checked_at: Timestamp | null;
  email: string;
  id: Generated<string>;
  owner_user_id: string | null;
  provider: Generated<string>;
  spf_status: Generated<DnsCheck>;
  status: Generated<AccountStatus>;
  workspace_id: string;
}

export interface EmailVerificationTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface EncryptionKeys {
  algorithm: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  retired_at: Timestamp | null;
  wrapped_key: Buffer;
}

export interface Enrollments {
  campaign_id: string;
  current_step_id: string | null;
  enrolled_at: Generated<Timestamp>;
  finished_at: Timestamp | null;
  id: Generated<string>;
  lead_id: string;
  next_run_at: Timestamp | null;
  status: Generated<EnrollmentStatus>;
  workspace_id: string;
}

export interface HourlyStats {
  day: Timestamp;
  hour: number;
  replies: Generated<number>;
  sends: Generated<number>;
  workspace_id: string;
}

export interface Integrations {
  active: Generated<boolean>;
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  credentials_secret_id: string | null;
  id: Generated<string>;
  provider: string;
  workspace_id: string;
}

export interface Invitations {
  accepted_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  invited_by: string | null;
  role: Generated<MembershipRole>;
  token_hash: string;
  workspace_id: string;
}

export interface Invoices {
  amount_cents: number;
  external_id: string | null;
  id: Generated<string>;
  issued_at: Generated<Timestamp>;
  paid_at: Timestamp | null;
  status: string;
  subscription_id: string;
}

export interface Jobs {
  ab_variant_id: string | null;
  action: ActionType;
  attempts: Generated<number>;
  batch_id: string | null;
  campaign_id: string | null;
  created_at: Generated<Timestamp>;
  email_account_id: string | null;
  enrollment_id: string | null;
  id: Generated<string>;
  idempotency_key: string | null;
  kind: Channel;
  last_error: string | null;
  lead_id: string | null;
  linkedin_account_id: string | null;
  payload: Generated<Json>;
  scheduled_for: Timestamp;
  sent_at: Timestamp | null;
  status: Generated<JobStatus>;
  step_id: string | null;
  workspace_id: string;
}

export interface Leads {
  company: Generated<string>;
  created_at: Generated<Timestamp>;
  email: string | null;
  email_verified: Generated<boolean>;
  enrichment: Generated<Json>;
  first_name: string;
  full_name: string;
  id: Generated<string>;
  last_activity: string | null;
  linkedin_url: string | null;
  location: Generated<string>;
  source: string | null;
  status: Generated<LeadStatus>;
  tags: Generated<string[]>;
  title: Generated<string>;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface LinkedinAccounts {
  connected_at: Timestamp | null;
  country: string;
  created_at: Generated<Timestamp>;
  email: string;
  hours_end: Generated<string>;
  hours_start: Generated<string>;
  id: Generated<string>;
  last_sync_at: Timestamp | null;
  owner_user_id: string | null;
  password_secret_id: string | null;
  proxy_id: string | null;
  send_weekends: Generated<boolean>;
  session_secret_id: string | null;
  status: Generated<AccountStatus>;
  timezone: Generated<string>;
  totp_secret_id: string | null;
  twofa: Generated<TwofaStatus>;
  warmup_daily_limit: Generated<number>;
  warmup_target: Generated<number>;
  weekly_invite_cap: Generated<number>;
  workspace_id: string;
}

export interface Memberships {
  created_at: Generated<Timestamp>;
  role: Generated<MembershipRole>;
  user_id: string;
  workspace_id: string;
}

export interface Messages {
  body: string;
  channel: Channel;
  direction: MessageDirection;
  external_id: string | null;
  id: Generated<string>;
  sent_at: Generated<Timestamp>;
  subject: string | null;
  thread_id: string;
}

export interface MfaBackupCodes {
  code_hash: string;
  id: Generated<string>;
  used_at: Timestamp | null;
  user_id: string;
}

export interface MigrationsLog {
  applied_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
}

export interface Notifications {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  read_at: Timestamp | null;
  refs: Generated<Json>;
  text: string;
  user_id: string | null;
  workspace_id: string;
}

export interface OauthIdentities {
  created_at: Generated<Timestamp>;
  email: string | null;
  id: Generated<string>;
  provider: string;
  provider_user_id: string;
  user_id: string;
}

export interface PasswordResetTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface Plans {
  currency: Generated<string>;
  features: Generated<Json>;
  id: string;
  max_linkedin_accounts: number;
  name: string;
  price_cents: number;
}

export interface Proxies {
  country: string;
  created_at: Generated<Timestamp>;
  healthy: Generated<boolean>;
  id: Generated<string>;
  ip: string;
  last_check: Timestamp | null;
  provider: string;
}

export interface Secrets {
  ciphertext: Buffer;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  key_id: string;
  kind: SecretKind;
  nonce: Buffer;
  rotated_at: Timestamp | null;
  user_id: string | null;
  workspace_id: string | null;
}

export interface Subscriptions {
  canceled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  current_period_end: Timestamp | null;
  current_period_start: Timestamp | null;
  external_customer_id: string | null;
  id: Generated<string>;
  plan_id: string;
  status: Generated<SubscriptionStatus>;
  workspace_id: string;
}

export interface Templates {
  body: string;
  channel: Channel;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  name: string;
  subject: string | null;
  workspace_id: string;
}

export interface TemplateStats {
  accept_pct: Numeric | null;
  template_id: string | null;
  used: Int8 | null;
  workspace_id: string | null;
}

export interface Threads {
  channel: Channel;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  labels: Generated<string[]>;
  last_message_at: Timestamp | null;
  lead_id: string;
  notes: string | null;
  unread: Generated<boolean>;
  workspace_id: string;
}

export interface UserMfa {
  enabled_at: Timestamp | null;
  last_used_at: Timestamp | null;
  totp_secret_id: string | null;
  user_id: string;
}

export interface Users {
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  disabled_at: Timestamp | null;
  email: string;
  email_verified_at: Timestamp | null;
  full_name: string;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  password_hash: string | null;
}

export interface UserSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  last_used_at: Generated<Timestamp>;
  refresh_token_hash: string;
  revoked_at: Timestamp | null;
  rotated_at: Timestamp | null;
  replaced_by: string | null;
  user_agent: string | null;
  user_id: string;
}

export interface WebhookDeliveries {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  endpoint_id: string;
  event_type: string;
  id: Generated<string>;
  next_retry_at: Timestamp | null;
  payload: Json;
  status: Generated<DeliveryStatus>;
}

export interface WebhookEndpoints {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  events: Generated<string[]>;
  id: Generated<string>;
  secret: string;
  url: string;
  workspace_id: string;
}

export interface Workspaces {
  branding: Generated<Json>;
  created_at: Generated<Timestamp>;
  goal: Generated<string>;
  id: Generated<string>;
  name: string;
  onboarding_done: Generated<boolean>;
  onboarding_step: Generated<number>;
}

export interface AiConversations {
  id: Generated<string>;
  workspace_id: string;
  user_id: string | null;
  title: Generated<string>;
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface AiMessages {
  id: Generated<string>;
  conversation_id: string;
  workspace_id: string;
  role: string;
  content: Generated<string>;
  tools: Json | null;
  created_at: Generated<Timestamp>;
}

export interface DB {
  ab_tests: AbTests;
  ai_conversations: AiConversations;
  ai_messages: AiMessages;
  ab_variants: AbVariants;
  activity: Activity;
  api_keys: ApiKeys;
  audit_log: AuditLog;
  blacklist: Blacklist;
  campaign_stats: CampaignStats;
  campaign_steps: CampaignSteps;
  campaigns: Campaigns;
  daily_stats: DailyStats;
  email_accounts: EmailAccounts;
  email_verification_tokens: EmailVerificationTokens;
  encryption_keys: EncryptionKeys;
  enrollments: Enrollments;
  hourly_stats: HourlyStats;
  integrations: Integrations;
  invitations: Invitations;
  invoices: Invoices;
  jobs: Jobs;
  leads: Leads;
  linkedin_accounts: LinkedinAccounts;
  memberships: Memberships;
  messages: Messages;
  mfa_backup_codes: MfaBackupCodes;
  migrations_log: MigrationsLog;
  notifications: Notifications;
  oauth_identities: OauthIdentities;
  password_reset_tokens: PasswordResetTokens;
  plans: Plans;
  proxies: Proxies;
  secrets: Secrets;
  subscriptions: Subscriptions;
  template_stats: TemplateStats;
  templates: Templates;
  threads: Threads;
  user_mfa: UserMfa;
  user_sessions: UserSessions;
  users: Users;
  webhook_deliveries: WebhookDeliveries;
  webhook_endpoints: WebhookEndpoints;
  workspaces: Workspaces;
}
