/**
 * Session-cookie policy, without a browser:
 *  1. Never inject the vault's cookie over a signed-in profile's own.
 *  2. Store the whole jar; `li_at` alone can't restore a session.
 *  3. Type a TOTP code only into the authenticator challenge; a wrong PIN is a
 *     failed login.
 */
import {
  parseStoredSession,
  serializeSession,
  cookiesToInject,
  classifyPinChallenge,
  LI_AT_DOMAIN,
  type StoredCookie,
} from '@/modules/drivers/linkedin-session-store';

/** A realistic jar, shaped exactly like `context.cookies()` returns. */
const liveJar: StoredCookie[] = [
  { name: 'li_at', value: 'LIVE_LI_AT', domain: '.www.linkedin.com', path: '/' },
  { name: 'JSESSIONID', value: '"ajax:123"', domain: '.www.linkedin.com', path: '/' },
  { name: 'bcookie', value: 'v=2&abc', domain: '.linkedin.com', path: '/' },
  { name: 'liap', value: 'true', domain: '.linkedin.com', path: '/' },
];

describe('stored session — the whole jar, not just li_at', () => {
  it('round-trips every cookie, not only li_at', () => {
    const restored = parseStoredSession(serializeSession(liveJar));

    expect(restored.map((c) => c.name).sort()).toEqual(
      ['JSESSIONID', 'bcookie', 'li_at', 'liap'],
    );
  });

  it('preserves each cookie\'s own domain instead of flattening them', () => {
    const restored = parseStoredSession(serializeSession(liveJar));

    expect(restored.find((c) => c.name === 'li_at')?.domain).toBe('.www.linkedin.com');
    expect(restored.find((c) => c.name === 'bcookie')?.domain).toBe('.linkedin.com');
  });

  it('BACK-COMPAT: reads an account stored under the old bare-li_at format', () => {
    // Accounts stored before the jar hold a plain string; they must keep working.
    const restored = parseStoredSession('OLD_FORMAT_LI_AT');

    expect(restored).toEqual([
      { name: 'li_at', value: 'OLD_FORMAT_LI_AT', domain: LI_AT_DOMAIN, path: '/' },
    ]);
  });

  it('restores a legacy cookie on the domain LinkedIn actually sets it on', () => {
    expect(LI_AT_DOMAIN).toBe('.www.linkedin.com');
  });

  it('treats an unusable stored value as no session at all', () => {
    expect(parseStoredSession('')).toEqual([]);
    expect(parseStoredSession(undefined)).toEqual([]);
    expect(parseStoredSession('[]')).toEqual([]);
  });
});

describe('cookie injection — the persistent profile owns the session', () => {
  it('THE BUG: never overwrites a profile that is already signed in', () => {
    // The profile has a live li_at and the vault an older one: inject nothing.
    const stored: StoredCookie[] = [
      { name: 'li_at', value: 'STALE_FROM_DB', domain: LI_AT_DOMAIN, path: '/' },
    ];

    expect(cookiesToInject(liveJar, stored)).toEqual([]);
  });

  it('seeds a fresh profile from the stored jar', () => {
    // A fresh profile (new machine, or %TEMP% cleared): the stored jar is all we have.
    expect(cookiesToInject([], liveJar)).toEqual(liveJar);
  });

  it('seeds a profile that has other LinkedIn cookies but no li_at', () => {
    const noSession = liveJar.filter((c) => c.name !== 'li_at');

    expect(cookiesToInject(noSession, liveJar)).toEqual(liveJar);
  });

  it('injects nothing when there is nothing stored', () => {
    expect(cookiesToInject([], [])).toEqual([]);
  });

  it('ignores a profile li_at that is present but empty', () => {
    const blank: StoredCookie[] = [
      { name: 'li_at', value: '', domain: LI_AT_DOMAIN, path: '/' },
    ];

    expect(cookiesToInject(blank, liveJar)).toEqual(liveJar);
  });
});

describe('PIN challenge — answer only the challenge we can actually answer', () => {
  it('recognises the authenticator-app challenge, which we CAN answer', () => {
    expect(
      classifyPinChallenge('Enter the 6-digit code from your authenticator app'),
    ).toBe('totp');
    expect(
      classifyPinChallenge('Please enter the verification code generated by your authenticator app'),
    ).toBe('totp');
  });

  it('recognises an emailed code, which no stored seed can generate', () => {
    expect(
      classifyPinChallenge("We've sent a verification code to j***@gmail.com"),
    ).toBe('email');
    expect(classifyPinChallenge('Enter the code we sent to your email')).toBe('email');
  });

  it('recognises an SMS code, which no stored seed can generate', () => {
    expect(
      classifyPinChallenge('We sent a code to your phone number ending in 42'),
    ).toBe('sms');
  });

  it('does not guess when the challenge text is unfamiliar', () => {
    // Unrecognised wording must not be taken for the authenticator challenge.
    expect(classifyPinChallenge('Quick security check')).toBe('unknown');
    expect(classifyPinChallenge('')).toBe('unknown');
  });

  it('reads an email challenge even when the page also names the app', () => {
    // The email page may link "use your authenticator app instead"; it still wants the emailed code.
    expect(
      classifyPinChallenge(
        "We've sent a verification code to your email. Use your authenticator app instead",
      ),
    ).toBe('email');
  });
});
